// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCeSYzGo4AEVRsDkVmODNUVt1DGDW9e3w',
    appId: '1:386362481596:web:e855ce6865815ee54069b9',
    messagingSenderId: '386362481596',
    projectId: 'doodle-cbdc8',
    authDomain: 'doodle-cbdc8.firebaseapp.com',
    databaseURL: 'https://doodle-cbdc8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doodle-cbdc8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv-OSQPO4ci0_gsyw1_v0BRoZkvLcWWDk',
    appId: '1:386362481596:android:c08b1dc8e9556d6c4069b9',
    messagingSenderId: '386362481596',
    projectId: 'doodle-cbdc8',
    databaseURL: 'https://doodle-cbdc8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doodle-cbdc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf1T9fQw56b6BoFi1xCXLkINLrZXh5QlU',
    appId: '1:386362481596:ios:866d5f385e73e5794069b9',
    messagingSenderId: '386362481596',
    projectId: 'doodle-cbdc8',
    databaseURL: 'https://doodle-cbdc8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doodle-cbdc8.appspot.com',
    androidClientId: '386362481596-12de1ar4fl48jfr8gts9e8oq3pfpulc8.apps.googleusercontent.com',
    iosClientId: '386362481596-s91qdlgcjgaf5ape5tcgpb94m2io5j9j.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
